Repository sage-os-team/sage-os, pull requests merged in 2022-03, with the labels that each got.

#4 feat: complete log debug module
  abstract-machine/klib/include/logger.h
  abstract-machine/klib/src/logger.c
  tests/example/tests/test_log.c
Labels: feat

#6 Dev 1 pmm
  .clang-format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/doxygen.yml
  Doxyfile
  abstract-machine/.gitignore
  abstract-machine/am/.clang-format
  abstract-machine/klib/include/logger.h
  abstract-machine/klib/src/logger.c
  docs/style/header.html
  kernel/framework/kernel.h
  kernel/include/buddy.h
  kernel/include/list.h
  kernel/src/buddy.c
  kernel/src/os.c
  kernel/src/pmm.c
  tests/example/include/trap.h
  tests/example/tests/add.c
  tests/example/tests/bit.c
  tests/example/tests/test_log.c
Labels: good first issue, feat

#12 重构测试框架
  .gitignore
  .vscode/.gitignore
  .vscode/launch.json.template
  .vscode/tasks.json.template
  abstract-machine/klib/src/stdio.c
  abstract-machine/klib/src/stdlib.c
  abstract-machine/klib/src/string.c
  test/.gitignore
  test/Makefile
  test/README.md
  test/include/trap.h
  test/units/add.c
  test/units/bit.c
  test/units/string.c
  test/units/test_log.c
  tests/example/Makefile
  tests/example/README.md
Labels: feat

#16 完成测试框架
  .vscode/launch.json.template
  Doxyfile
  kernel/src/os.c
  test/Makefile
  test/README.md
  test/units/kernel_example.c
Labels: enhancement
