Repository sage-os-team/sage-os, pull requests merged in 2022-04, with the labels that each got.

#8 Dev 1 pmm: impl of buddy system(tested)
  abstract-machine/klib/include/logger.h
  kernel/framework/kernel.h
  kernel/include/buddy.h
  kernel/include/common.h
  kernel/include/list.h
  kernel/src/buddy.c
  kernel/src/os.c
  kernel/src/pmm.c
Labels: enhancement, feat

#20 Dev 2 kmt
  kernel/framework/kernel.h
  kernel/include/buddy.h
  kernel/include/common.h
  kernel/include/list.h
  kernel/include/thread.h
  kernel/src/buddy.c
  kernel/src/kmt.c
  kernel/src/os.c
  kernel/src/pmm.c
Labels: feat

#23 Dev 4a klib
  .gitignore
  .vscode/.gitignore
  .vscode/c_cpp_properties.json.template
  .vscode/launch.json.template
  .vscode/tasks.json.template
  Doxyfile
  abstract-machine/klib/include/klib.h
  abstract-machine/klib/include/logger.h
  abstract-machine/klib/src/stdio.c
  abstract-machine/klib/src/stdlib.c
  abstract-machine/klib/src/string.c
  kernel/src/os.c
  test/.gitignore
  test/Makefile
  test/README.md
  test/include/trap.h
  test/units/add.c
  test/units/bit.c
  test/units/kernel_example.c
  test/units/stdio.c
  test/units/string.c
  test/units/test_log.c
  tests/example/Makefile
  tests/example/README.md
Labels: feat

#24 Dev 1 pmm 页面计算bug
  kernel/src/buddy.c
  kernel/src/pmm.c
Labels: bug

#29 Dev 4a klib
  abstract-machine/klib/src/stdio.c
  test/Makefile
  test/README.md
  test/units/kernel_example.c
  test/units/stdio.c
  test/units/test_add.c
  test/units/test_bit.c
  test/units/test_stdio.c
  test/units/test_string.c
  test/units/thread-os.c
Labels: bug
